-- 1. Создание таблицы
CREATE TABLE IF NOT EXISTS dishes (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  name_lt TEXT NOT NULL,
  name_ru TEXT,
  name_en TEXT,
  weight TEXT,
  price_student DECIMAL(10, 2),
  price_teacher DECIMAL(10, 2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Вставка данных
INSERT INTO dishes (id, category, name_lt, name_ru, name_en, weight, price_student, price_teacher)
VALUES 
('s1', 'sriubos', 'Agurkinė sriuba', 'Огуречный суп', 'Cucumber soup', '250/20', 0.25, 0.28),
('s2', 'sriubos', 'Barščiai su pupelemis', 'Борщ с фасолью', 'Borscht with beans', '250/20', 0.31, 0.34),
('s3', 'sriubos', 'Bulvių sriuba su lęšiais', 'Картофельный суп с чечевицей', 'Potato soup with lentils', '250', 0.22, 0.22),
('s4', 'sriubos', 'Bulvių sriuba su mėsos kukuliukais', 'Картофельный суп с фрикадельками', 'Potato soup with meatballs', '250', 0.57, 0.63),
('s5', 'sriubos', 'Bulvių sriuba su pupelėmis', 'Картофельный суп с фасолью', 'Potato soup with beans', '250', 0.21, 0.23),
('s6', 'sriubos', 'Burokėlių sriuba su grietine', 'Свекольник со сметаной', 'Beetroot soup with sour cream', '250/20', 0.35, 0.39),
('s7', 'sriubos', 'Burokėlių sriuba su pupelėmis', 'Свекольный суп с фасолью', 'Beetroot soup with beans', '250/20', 0.36, 0.40),
('s8', 'sriubos', 'Daržovių ir viso grūdo makaronų sriuba', 'Суп из овощей и цельнозерновых макарон', 'Vegetable and whole grain pasta soup', '250', 0.37, 0.41),
('s9', 'sriubos', 'Lakštinių sriuba su grybais', 'Суп с лапшой и грибами', 'Noodle soup with mushrooms', '250', 0.22, 0.24),
('s10', 'sriubos', 'Naminė agurkė sriuba', 'Домашний огуречный суп', 'Homemade cucumber soup', '250/20', 0.39, 0.43),
('s11', 'sriubos', 'Naminė šiupininė sriuba', 'Домашний суп с перловой крупой', 'Homemade pearl barley soup', '250', 0.67, 0.74),
('s12', 'sriubos', 'Naminių lakštinių sriuba su vištiena', 'Домашний суп с лапшой и курицей', 'Homemade noodle soup with chicken', '250', 0.30, 0.33),
('s13', 'sriubos', 'Netikras zuikis su kiauliena', 'Зайчик с свининой', 'Meatloaf with pork', '100', 0.94, 1.03),
('s14', 'sriubos', 'Pertrinta brokolių sriuba', 'Суп-пюре из брокколи', 'Cream of broccoli soup', '250', 0.37, 0.41),
('s15', 'sriubos', 'Pertrinta grybu sriuba', 'Грибной суп-пюре', 'Cream of mushroom soup', '250/20', 0.48, 0.53),
('s16', 'sriubos', 'Pieniška grikių kruopų sriuba su sviestu', 'Молочный суп из гречки со сливочным маслом', 'Milk soup with buckwheat and butter', '250', 0.30, 0.33),
('s17', 'sriubos', 'Pieniška makaronų sriuba', 'Молочный суп с макаронами', 'Milk soup with pasta', '150', 0.10, 0.11),
('s18', 'sriubos', 'Pieniška ryžių sriuba', 'Молочный рисовый суп', 'Milk soup with rice', '250', 0.09, 0.10),
('s19', 'sriubos', 'Poltavos barščiai', 'Полтавский борщ', 'Poltava style borscht', '250/20', 0.19, 0.21),
('s20', 'sriubos', 'Pupelių sriuba su bulvėmis', 'Фасолевый суп с картофелем', 'Bean soup with potatoes', '250', 0.17, 0.19),
('s21', 'sriubos', 'Pupelių sriuba su bulvėmis ir cukinijomis', 'Фасолевый суп с картофелем и кабачками', 'Bean soup with potatoes and zucchini', '250', 0.43, 0.47),
('s22', 'sriubos', 'Raugintų kopūstų sriuba', 'Суп из квашеной капусты', 'Sauerkraut soup', '250/20', 0.44, 0.48),
('s23', 'sriubos', 'Raugintų kopūstų sriuba su grietine', 'Суп из квашеной капусты со сметаной', 'Sauerkraut soup with sour cream', '250/20', 0.53, 0.58),
('s24', 'sriubos', 'Rūgštynių sriuba su grietine', 'Щавелевый суп со сметаной', 'Sorrel soup with sour cream', '250/20', 0.43, 0.47),
('s25', 'sriubos', 'Rūgštynių sriuba su tomatu', 'Щавелевый суп с томатом', 'Sorrel soup with tomato', '250/20', 0.37, 0.41),
('s26', 'sriubos', 'Šaltibarščiai', 'Холодный борщ (шалтибарщяй)', 'Cold beetroot soup (Saltibarsciai)', '250/10/20', 0.77, 0.85),
('s27', 'sriubos', 'Sibiro barščiai', 'Сибирский борщ', 'Siberian borscht', '250/20', 0.12, 0.13),
('s28', 'sriubos', 'Šiupininė sriuba', 'Суп с перловой крупой', 'Solianka / Barley soup', '250/10', 0.55, 0.61),
('s29', 'sriubos', 'Sriuba „Charčio“', 'Суп харчо', 'Kharcho soup', '250', 0.78, 0.86),
('s30', 'sriubos', 'Sultinys su kepta juoda duona', 'Бульон с черным хлебом', 'Broth with fried rye bread', '200/50', 0.10, 0.11),
('s31', 'sriubos', 'Sultinys su pakepinta balta duona', 'Бульон с гренками', 'Broth with croutons', '200/30', 0.14, 0.15),
('s32', 'sriubos', 'Šv.daržovių sriuba', 'Светлый овощной суп', 'Fresh vegetable soup', '250/20', 0.40, 0.44),
('s33', 'sriubos', 'Šviežių kopūstų sriuba', 'Суп из свежей капусты', 'Fresh cabbage soup', '250', 0.40, 0.44),
('s34', 'sriubos', 'Šviežių kopūstų sriuba su grietine', 'Суп из свежей капусты со сметаной', 'Fresh cabbage soup with sour cream', '250/20', 0.45, 0.50),
('s35', 'sriubos', 'Tiršta agurkinė sriuba(bulv,mork,perl.kruop)', 'Густой огуречный суп (картофель, морковь, перловка)', 'Thick cucumber soup (potatoes, carrots, barley)', '250/20', 0.39, 0.43),
('s36', 'sriubos', 'Tiršta burokėlių ir pupelių sriuba su bulvėmis.', 'Густой свекольно-фасолевый суп с картофелем', 'Thick beetroot and bean soup with potatoes', '250/20', 0.42, 0.46),
('s37', 'sriubos', 'Trinta cukinijų sriuba', 'Суп-пюре из кабачков', 'Creamy zucchini soup', '250', 0.45, 0.50),
('s38', 'sriubos', 'Trinta daržovių sriuba', 'Овощной суп-пюре', 'Creamy vegetable soup', '250', 0.27, 0.30),
('s39', 'sriubos', 'Trinta moliūгų sriuba', 'Суп-пюре из тыквы', 'Creamy pumpkin soup', '250/20', 0.42, 0.46),
('s40', 'sriubos', 'Trinta pomidorų sriuba', 'Томатный суп-пюре', 'Creamy tomato soup', '250/20', 0.43, 0.47),
('s41', 'sriubos', 'Trinta špinatų-žirnių sriuba', 'Суп-пюре из шпината и гороха', 'Creamy spinach and pea soup', '250', 0.64, 0.70),
('s42', 'sriubos', 'Trinta žiedinių kopūstų sriuba', 'Суп-пюре из цветной капусты', 'Creamy cauliflower soup', '300', 0.16, 0.18),
('s43', 'sriubos', 'Trinta žiedinių kopūstų sriuba su pienu', 'Суп-пюре из цветной капусты с молоком', 'Creamy cauliflower soup with milk', '250', 0.25, 0.28),
('s44', 'sriubos', 'Ukrainietiški barščiai', 'Украинский борщ', 'Ukrainian borscht', '250/20', 0.35, 0.39),
('s45', 'sriubos', 'Žirnių sriuba', 'Гороховый суп', 'Pea soup', '250', 0.19, 0.21),
('s46', 'sriubos', 'Žirnių sriuba su bulvėmis ir morkomis', 'Гороховый суп с картофелем и морковью', 'Pea soup with potatoes and carrots', '250', 0.17, 0.19),
('m1', 'main', 'Apkepta kiauliena su džiov. abrikosais', 'Свинина с курагой', 'Roasted pork with dried apricots', '100/50', 1.93, 2.12),
('m2', 'main', 'Apkepta kiaulienos sprandinė', 'Жареная свиная шейка', 'Roasted pork neck', '100', 1.24, 1.36),
('m3', 'main', 'Apkeptas kotletas su pieno padažu', 'Котлета с молочным соусом', 'Roasted cutlet with milk sauce', '140', 0.88, 0.97),
('m4', 'main', 'Balandėliai su padažu', 'Голубцы с соусом', 'Cabbage rolls with sauce', '216/100', 1.09, 1.10),
('m5', 'main', 'Befstrogenas', 'Бефстроганов', 'Beef Stroganoff', '75/75', 2.17, 2.39),
('m6', 'main', 'Biguzas', 'Бигус', 'Bigos (cabbage stew)', '275', 1.23, 1.35),
('m7', 'main', 'Biri žalių grikių košė su sviestu(tausojantis)', 'Гречневая каша со сливочным маслом', 'Buckwheat porridge with butter', '150', 0.41, 0.45),
('m8', 'main', 'Bulgur su daržovėmis', 'Булгур с овощами', 'Bulgur with vegetables', '150', 0.12, 0.13),
('m9', 'main', 'Bulgur su sviestu', 'Булгур со сливочным маслом', 'Bulgur with butter', '150', 0.21, 0.23),
('m10', 'main', 'Bulvių blynai su grybais', 'Картофельные оладьи с грибами', 'Potato pancakes with mushrooms', '200/50', 0.65, 0.72),
('m11', 'main', 'Bulvių dubenėliai su spirgūčiais ir grietine', 'Картофельные крокеты со шкварками и сметаной', 'Potato croquettes with cracklings and sour cream', '200/35/30', 1.05, 1.10),
('m12', 'main', 'Bulvių ir morkų košė', 'Картофельно-морковное пюре', 'Potato and carrot mash', '150', 0.17, 0.19),
('m13', 'main', 'Bulvių košė', 'Картофельное пюре', 'Mashed potatoes', '150', 0.22, 0.24),
('m14', 'main', 'Bulvių košė su sviestu', 'Картофельное пюре со сливочным маслом', 'Mashed potatoes with butter', '150', 0.22, 0.24),
('m15', 'main', 'Bulvių plokštainis su grietine', 'Картофельная запеканка со сметаной', 'Potato pudding (Kugelis) with sour cream', '200/50', 1.16, 1.28),
('m16', 'main', 'Eskalopas su griet.-daržovių padažu', 'Эскалоп с сметано-овощным соусом', 'Escalope with sour cream and vegetable sauce', '100/50', 1.47, 1.62),
('m17', 'main', 'Grietinelėje troškinta vištienos krūtinėlė su mork', 'Куриная грудка в сметане с морковью', 'Chicken breast stewed in sour cream with carrots', '200', 1.30, 1.43),
('m18', 'main', 'Grikių košė', 'Гречневая каша', 'Buckwheat porridge', '150', 0.20, 0.22),
('m19', 'main', 'Grikių košė su morkomis ir svogūnais', 'Гречневая каша с морковью и луком', 'Buckwheat porridge with carrots and onions', '150', 0.24, 0.26),
('m20', 'main', 'Husaro šnicelis', 'Шницель по-гусарски', 'Hussar style schnitzel', '120', 1.33, 1.46),
('m21', 'main', 'Kiaulienos kepsnys', 'Жареная свинина', 'Pork steak', '100', 1.20, 1.32),
('m22', 'main', 'Kiaulienos kotletas', 'Свиная котлета', 'Pork cutlet', '100', 0.59, 0.65),
('m23', 'main', 'Lietuviškas karbonadas', 'Литовский карбонад', 'Lithuanian pork schnitzel', '100', 1.11, 1.22),
('m24', 'main', 'Plovas', 'Плов', 'Pilaf', '350', 1.54, 1.69),
('m25', 'main', 'Ryžių plovas su vištienos filė', 'Рисовый плов с куриным филе', 'Rice pilaf with chicken fillet', '300', 1.65, 1.81),
('m26', 'main', 'Virta vištienos filė', 'Отварное куриное филе', 'Boiled chicken fillet', '100', 1.26, 1.39),
('m27', 'main', 'Virti makaronai', 'Отварные макароны', 'Boiled pasta', '150', 0.20, 0.22),
('m28', 'main', 'Virti ryžiai', 'Отварной рис', 'Boiled rice', '150', 0.18, 0.20),
('m29', 'main', 'Virtos bulvės', 'Отварной картофель', 'Boiled potatoes', '150', 0.20, 0.22),
('m30', 'main', 'Žemaičių blynai', 'Жемайтийские оладьи', 'Samogitian potato pancakes', '200/50', 1.52, 1.67),
('a1', 'salotos', 'Baltųjų ridikų ir morkų salotos', 'Салат из редиса и моркови', 'White radish and carrot salad', '130', 0.46, 0.51),
('a2', 'salotos', 'Burokėliai su aliejumi', 'Свекла с маслом', 'Beets with oil', '100/10', 0.12, 0.13),
('a3', 'salotos', 'Burokėlių salotos su raug.kopūstais', 'Салат из свеклы с квашеной капустой', 'Beetroot salad with sauerkraut', '100', 0.23, 0.25),
('a4', 'salotos', 'Daržovių salotos su alyv.aliejumi', 'Овощной салат с оливковым маслом', 'Vegetable salad with olive oil', '140', 0.39, 0.43),
('a5', 'salotos', 'Graikinės salotos', 'Греческий салат', 'Greek salad', '150', 0.94, 1.03),
('a6', 'salotos', 'Itališkos salotos', 'Итальянский салат', 'Italian salad', '170', 1.01, 1.11),
('a7', 'salotos', 'Kopūstų ir morkų salotos', 'Салат из капусты и моркови', 'Cabbage and carrot salad', '90', 0.19, 0.21),
('a8', 'salotos', 'Kopūstų salotos su paprika', 'Салат из капусты с перцем', 'Cabbage salad with bell pepper', '100', 0.18, 0.20),
('a9', 'salotos', 'Kopūstų salotos su pomidorais', 'Салат из капусты с томатами', 'Cabbage salad with tomatoes', '100', 0.19, 0.21),
('a10', 'salotos', 'Mišrainė', 'Винегрет', 'Vinaigrette salad', '100', 0.23, 0.25),
('a11', 'salotos', 'Salotos su Mozzarella', 'Салат с моцареллой', 'Salad with mozzarella', '130', 1.43, 1.57),
('a12', 'salotos', 'Švieži agurkai', 'Свежие огурцы', 'Fresh cucumbers', '65', 0.13, 0.14),
('a13', 'salotos', 'Šviežių kopūstų salotos', 'Салат из свежей капусты', 'Fresh cabbage salad', '100', 0.17, 0.19),
('a14', 'salotos', 'Vitaminizuotos salotos', 'Витаминный салат', 'Vitamin salad', '100', 0.12, 0.13),
('d1', 'drinks', 'Kefyras', 'Кефир', 'Kefir', '200', 0.32, 0.35),
('d2', 'drinks', 'Mineralinis negazuotas vanduo', 'Минеральная вода без газа', 'Still mineral water', '200', 0.10, 0.11),
('d3', 'drinks', 'Vaisių kompotas', 'Фруктовый компот', 'Fruit compote', '180', 0.12, 0.13),
('d4', 'drinks', 'Vanduo su citrina', 'Вода с лимоном', 'Water with lemon', '200/5', 0.01, 0.01),
('o1', 'other', 'Kuskusas', 'Кускус', 'Couscous', '150', 0.13, 0.14),
('o2', 'other', 'Morkų -svog ir česnak.padažas su ciberžole', 'Соус из моркови, лука и чеснока с укропом', 'Carrot, onion and garlic sauce with turmeric', '60', 0.07, 0.08),
('o3', 'other', 'Morkų ir svogūnų su česnaku padažas', 'Соус из моркови и лука с чесноком', 'Carrot and onion sauce with garlic', '60', 0.04, 0.04),
('o4', 'other', 'Nesaldintas jogurtas', 'Несладкий йогурт', 'Unsweetened yogurt', '50', 0.33, 0.36),
('o5', 'other', 'Švies. kviet. duona', 'Белый пшеничный хлеб', 'White wheat bread', '20-25', 0.04, 0.04),
('o6', 'other', 'Viso grūdo rūginė duona', 'Цельнозерновой ржаной хлеб', 'Whole grain rye bread', '20-25', 0.04, 0.04)
ON CONFLICT (id) DO UPDATE SET
  category = EXCLUDED.category,
  name_lt = EXCLUDED.name_lt,
  name_ru = EXCLUDED.name_ru,
  name_en = EXCLUDED.name_en,
  weight = EXCLUDED.weight,
  price_student = EXCLUDED.price_student,
  price_teacher = EXCLUDED.price_teacher,
  updated_at = CURRENT_TIMESTAMP;
